(function(){
	angular.module("successCtrlModule",[])
		.controller("paysuccessController",[
			"$scope","$state",
			function($scope,$state){
				$scope.goHome=function(){
					$state.go("scan");
				}
			}
		])
})()
