(function(){
	angular.module("BookStroreApp",[
		"ionic",
		"ngSanitize",
		"hostConfigModule",
		"appRouterModule",
		"introCtrlModule",
		"modalDataModule",
		"postDataModule",
		"loginCtrlModule",
		"registCtrlModule",
		"getDataModule",
		"listCtrlModule",
		"ionicMessageModule",
		"cartDataModule",
		"cartListCtrlModule",
		"detailCtrlModule",
		"userCtrlModule",
		"showOrderCtrlModule"
		]);
})()